# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoAWS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demoAWS
pod ‘AWSIoT’, ‘~>2.6.0'
#pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
#pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'demoAWS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


    #pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

  end

  target 'demoAWSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

